server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: appointment-service
          uri: http://localhost:8082
          predicates:
            - Path=/appointments/**
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
